---
title: "`r params$title`"
output: html_document
params:
  title: "Analyse des modèles A et B"
  file_key: "260232192901model"
---

Analyse des sorties des modèles A et B

```{r setup, include=FALSE}

Sys.setlocale("LC_ALL", "fr_FR.UTF-8")
options(encoding = "UTF-8")

knitr::opts_chunk$set(
  echo    = FALSE,
  message = FALSE,
  warning = FALSE
)

library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(knitr)
library(kableExtra)

# Fonction standard pour afficher les tableaux
print_table <- function(df, caption = NULL, digits = 3) {
  knitr::kable(
    df,
    format   = "html",
    caption  = caption,
    digits   = digits
  ) %>%
    kableExtra::kable_styling(
      bootstrap_options = c("striped", "hover", "condensed"),
      full_width = FALSE,
      position = "left"
    )
}

# identifiant des fichiers de la simulation
file_key <- params$file_key

# récupération des données
output_dir <- "output"
dataA_file  <- file.path(output_dir, paste0(file_key, "A.output.csv"))
dataB_file  <- file.path(output_dir, paste0(file_key, "B.output.csv"))
param_file <- file.path(output_dir, paste0(file_key, "A.parameters.csv"))

dfA        <- read.csv(dataA_file)
dfB        <- read.csv(dataB_file)
params_df <- read.csv(param_file)


# Limite burn-in des données
tLim <- 200

# Nombre de secteurs repésentatifs à afficher

n_sample <- 9

# Tirage aléatoire de secteurs représentatifs parmi l'ensemble des secteurs

set.seed(NULL)
sample_sectors <- sample(unique(dfA$sector), n_sample)

```


```{r}

export_plot <- function(p, name, dir = "figures",
                        width = 7, height = 5, dpi = 300) {

  # créer le dossier si besoin
  if (!dir.exists(dir)) dir.create(dir, recursive = TRUE)

  # chemins
  pdf_path <- file.path(dir, paste0(name, ".pdf"))
  png_path <- file.path(dir, paste0(name, ".png"))

  # export PDF vectoriel
  pdf(pdf_path, width = width, height = height, family = "Helvetica")
  print(p)
  dev.off()

  # export PNG haute résolution
  ggsave(
    filename = png_path,
    plot = p,
    width = width,
    height = height,
    dpi = dpi
  )

  message("Exported: ", pdf_path, " and ", png_path)
}
```



# Au sujet de ce rapport

```{r}
cat("Date et heure de génération du rapport :", format(Sys.time(), "%d/%m/%Y %H:%M:%S"), "\n")

cat("Data source:", file_key, "\n")

number_of_sectors <- max(dfA$sector) + 1

```
# Paramètres généraux de la simulation


```{r}

# Préparation des données

wide_dfA <- dfA  %>% 
  filter(!is.na(value)) %>%
  pivot_wider(
    names_from = dataType,
    values_from = value
  )

```



```{r}
prices_dfA <- wide_dfA %>%
  group_by(t) %>%
  mutate(
    totalProductionValue = sum(productionValue, na.rm = TRUE),
    totalSectorSize      = sum(sectorSize, na.rm = TRUE),
    producedValue        = totalProductionValue * sectorSize / totalSectorSize,
    unitValue            = producedValue / productionVolume,
    gap                  = (price-unitValue)/unitValue
  ) %>%
  ungroup()
```

```{r}
prices_dfB <- dfB %>%
  filter(dataType %in% c(
    "productionValue",
    "productionVolume",
    "consumptionVolume",
    "consumptionValue",
    "sectorSize",
    "laborUsed"
  )) %>%
  pivot_wider(
    names_from = dataType,
    values_from = value
  )

prices_dfB <- prices_dfB %>%
  group_by(t) %>%
  mutate(
    totalProductionValue = sum(productionValue, na.rm = TRUE),
    totalConsumptionValue = sum(consumptionValue, na.rm = TRUE),
    totalSectorSize      = sum(sectorSize, na.rm = TRUE),
    unitPrice2            = consumptionValue / consumptionVolume,
    unitPrice           = productionValue / productionVolume,
    producedValue        = totalProductionValue * sectorSize / totalSectorSize,
    unitValue            = producedValue / productionVolume,
    totalLaborUsed       = sum(laborUsed, na.rm = TRUE),
    laborEquivalent      = totalConsumptionValue * laborUsed / totalLaborUsed,
    unitLaborEquivalent  = laborEquivalent / consumptionVolume
  ) %>%
  ungroup()

prices_dfB <- prices_dfB %>%
  mutate(
    relativePriceGap = (unitPrice - unitValue) / unitValue,
    relativePriceGap2 = (unitPrice2 - unitLaborEquivalent) / unitLaborEquivalent
  )



```



```{r}

resultB <- prices_dfB %>%
  #filter(t > tLim) %>%
  group_by(sector) %>%
  summarise(
    mean_sectorSize = mean(sectorSize, na.rm = TRUE),
    mean_relativePriceGap   = mean(relativePriceGap,   na.rm = TRUE),
    mean_relativePriceGap2   = mean(relativePriceGap2,   na.rm = TRUE)
  )

```


```{r}
A <- prices_dfA %>%
  group_by(sector) %>%
  filter(t == max(t)) %>%
  ungroup() %>%
  transmute(
    sector = factor(sector),
    x = sectorSize,
    y = (1+gap)*100,
    facet = "vA (équilibre général)"
  )

B <- resultB %>%
  transmute(
    sector = factor(sector),
    x = mean_sectorSize,
    y = (1+mean_relativePriceGap)*100,
    facet = "vb (dynamiques décentralisés))"
  )

 meanA <- mean(A$x)
 meanB <- mean(B$x)
 medianA <- median(A$x)
 medianB <- median(B$x)

combined <- bind_rows(A, B)

p <- ggplot(combined, aes(x = x, y = y, color = sector)) +
  geom_point(size = 2, alpha = 1) +
  facet_wrap(~ facet) +
  labs(
    x = "Taille du secteur (nombre d'agents)",
    y = "Rapport Prix / Valeur (%)"
  ) +
  geom_hline(yintercept=100, linetype = "dotted") +
  theme_minimal() +
  theme(legend.position = "none")

p <- p +
  geom_vline(
    data = subset(combined, facet == "A"),
    xintercept = medianA,
    linetype = "dotted"
  ) +
  geom_vline(
    data = subset(combined, facet == "B"),
    xintercept = medianB,
    linetype = "dotted"
  )

export_plot(p, "price2valueAB")

print(p)


```

```{r}
prices_dfB %>%
  ggplot(aes(t, color = factor(sector))) +
  geom_line(aes(y = unitPrice), linewidth = 0.5) +
  scale_y_log10() +
  labs(
    title = "Prix unitaires",
    x = "Temps",
    y = "Prix",
    #color = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r fig.height=8}

# Filtrer prices_df pour ces secteurs

wide_sample <- prices_dfB %>% filter(sector %in% sample_sectors)

# Burn-in

wide_sample <- wide_sample %>%
  filter(t > tLim)

# Tracé avec facettes

ggplot(wide_sample, aes(x = t)) +
  geom_line(aes(y = unitPrice2, color = "Prix à la consommation"), linewidth = 0.5) +
  geom_line(aes(y = unitPrice, color = "Prix à la production"), linewidth = 0.5) +
  scale_y_log10() +
  facet_wrap(~sector, scales = "fixed") +
  labs(
    title = paste("Prix et valeur unitaires –", n_sample, "secteurs représentatifs, t >", tLim),
    x = "Temps",
    y = "Grandeur unitaire",
    color = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

```

```{r}
ggplot(wide_sample, aes(x = t)) +
  geom_line(aes(y = unitPrice2/unitPrice, color = "Ratio = Prix à la consommation/Prix de production"), linewidth = 0.5) +
  facet_wrap(~sector, scales = "fixed") +
  labs(
    title = paste("Prix unitaires –", n_sample, "secteurs représentatifs, t >", tLim),
    x = "Temps",
    y = "Grandeur unitaire",
    color = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}

ggplot(wide_sample, aes(x = t)) +
  geom_line(aes(y = unitValue, color = "Valeur unitaire des marchandises consommées"), linewidth = 0.5) +
  geom_line(aes(y = unitLaborEquivalent, color = "Valeur unitaire des marchandises produites"), linewidth = 0.5) +
  scale_y_log10() +
  facet_wrap(~sector, scales = "fixed") +
  labs(
    title = paste("2 calculs des valeurs unitaires –", n_sample, "secteurs représentatifs, t >", tLim),
    x = "Temps",
    y = "Grandeur unitaire",
    color = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

```

```{r}

ggplot(wide_sample, aes(x = t)) +
  geom_line(aes(y = unitLaborEquivalent/unitValue, color = "Prix à la consommation"), linewidth = 0.5) +
  #scale_y_log10() +
  facet_wrap(~sector, scales = "fixed") +
  labs(
    title = paste("Deuw mesures de la valeur –", n_sample, "secteurs représentatifs, t >", tLim),
    x = "Temps",
    y = "Grandeur unitaire",
    color = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

```